package com.example.experiments2.card

enum class CardEnum {
    NO_CARD,
    BIRTHDAY, DEBT_COLLECTOR, DOUBLE_THE_RENT, ASSET_A, ASSET_B, ASSET_C, ASSET_D, ASSET_E,
    MONEY_1, MONEY_2, MONEY_3, MONEY_4, MONEY_5,
    RENT_CARD_A, RENT_CARD_B, RENT_CARD_C, RENT_CARD_D, RENT_CARD_E,
    PASS_GO, FORCED_DEAL, SAY_NO, SLY_DEAL, DEAL_BREAKER
}
